// Especificació visual dels 76 nodes. Cada entrada tradueix el «Diagrama central» del guió
// a una plantilla de src/diagrams.js. L’ordre ha de coincidir amb el número del node.
const specs = [
  /* 01 */ { type: "shell", labels: ["LA PART CREIX", "EL CONJUNT S’APRIMA"] },
  /* 02 */ { type: "columns", labels: ["CÀNCER", "CAPITALISME"], rows: ["CREIXEMENT SENSE FRE", "INVASIÓ", "METÀSTASI", "EVASIÓ DE DEFENSES"] },
  /* 03 */ { type: "converge", labels: ["CIRCUITS PROPIS DEL SISTEMA", "UN NODE REORIENTAT"], fromRing: true },
  /* 04 */ { type: "separate", labels: ["PERSONA", "MALALTIA", "SISTEMA ECONÒMIC"], link: [2, 1, "EXPOSICIÓ AL RISC"] },
  /* 05 */ { type: "fork", labels: ["PROCÉS SENSE INTENCIÓ", "DECISIÓ AMB SIGNATURA", "MATEIX RESULTAT"] },
  /* 06 */ { type: "contain", labels: ["1 DE CADA 5 · UNA PART", "TOTHOM · L’ENTORN"] },
  /* 07 */ { type: "network", mode: "defector", labels: ["COOPERACIÓ", "LA PART QUE FA TRAMPA"] },
  /* 08 */ { type: "sequence", rows: [["NECESSITAT", "CREIXEMENT", "FUNCIÓ", "ATURADA"], ["CREIXEMENT", "MÉS", "MÉS", "MÉS"]], loop: 1, cls: [[], ["danger-chip", "danger-chip", "danger-chip", "danger-chip"]] },
  /* 09 */ { type: "curves", kind: "logistic", labels: ["S’ATURA", "NO S’ATURA", "LÍMIT DEL SISTEMA"] },
  /* 10 */ { type: "rescue", labels: ["ELS PETITS DESAPAREIXEN", "MASSA GRAN PER CAURE", "RESCAT PÚBLIC"] },
  /* 11 */ { type: "light", labels: ["SENYAL D’ATURADA", "FRE DESCONNECTAT"] },
  /* 12 */ { type: "treadmill", labels: ["LA CINTA ACCELERA", "QUI S’ATURA CAU"] },
  /* 13 */ { type: "rounds", labels: ["DIVERSITAT INICIAL", "SELECCIÓ", "NOMÉS LA MÉS EXPANSIVA"] },
  /* 14 */ { type: "loop", labels: ["MÉS RECURSOS", "MÉS PODER"] },
  /* 15 */ { type: "spiral", labels: ["UN MÓN FINIT", "ORDRE INFINITA", "UN ALTRE COS?"] },
  /* 16 */ { type: "sequence", rows: [["M", "D", "M", "NECESSITAT"], ["D", "M", "D′", "D″ …"]], loop: 1, cls: [[], ["danger-chip", "danger-chip", "danger-chip", "danger-chip"]] },
  /* 17 */ { type: "converge", labels: ["ACCÉS A RECURSOS I A CONDICIONS DE VIDA", "QUI CONTROLA L’ACCÉS"] },
  /* 18 */ { type: "manyArrows", labels: ["DECISIONS LOCALS", "DIRECCIÓ GLOBAL"] },
  /* 19 */ { type: "chain", labels: ["PRESENT", "FUTUR", "DEUTE"] },
  /* 20 */ { type: "rent", labels: ["PROPIETARI", "LLOGUER · INTERÈS · PATENT · COMISSIÓ"] },
  /* 21 */ { type: "soil", labels: ["LLAVOR", "EL SÒL DECIDEIX SI CREIX"], items: ["VASOS", "TREBALL", "CURES", "LLEIS", "SILENCIS"] },
  /* 22 */ { type: "converge", mode: "pipes", labels: ["CANONADES COMUNES", "EL DIPÒSIT QUE BRILLA"] },
  /* 23 */ { type: "radial", mode: "inward", labels: ["CANALS CAP A LA PERIFÈRIA", "EL FLUX NOMÉS VA CAP AL CENTRE"] },
  /* 24 */ { type: "outlets", labels: ["ESTAT", "LÍMIT", "SUBVENCIÓ"] },
  /* 25 */ { type: "shield", mode: "turn", labels: ["L’ESCUT GIRA", "PROTEGEIX EL QUE HAVIA DE VIGILAR"] },
  /* 26 */ { type: "inflamed", labels: ["CRISI · FERIDA OBERTA", "MÉS CONCENTRACIÓ"] },
  /* 27 */ { type: "funnel", labels: ["ENERGIA", "FUNCIÓ ÚTIL", "RESIDUS"] },
  /* 28 */ { type: "product", labels: ["TREBALL", "CURES", "NATURA", "BENEFICI"] },
  /* 29 */ { type: "curves", kind: "reservoir", labels: ["DIPÒSIT FÒSSIL", "ACUMULACIÓ"] },
  /* 30 */ { type: "outflow", labels: ["CENTRE NET", "EL DANY VA A LES PERIFÈRIES"] },
  /* 31 */ { type: "ground", mode: "iceberg", labels: ["EL QUE COMPTA EL PIB", "CURES NO PAGADES QUE HO SOSTENEN"] },
  /* 32 */ { type: "converge", mode: "shrinking", labels: ["PERIFÈRIES QUE S’APRIMEN", "POCS CENTRES"], n: 10 },
  /* 33 */ { type: "sequence", rows: [["ESTÍMUL", "MANCA", "COMPRA", "NOVA MANCA"]], loop: true },
  /* 34 */ { type: "orbit", mode: "identities", labels: ["OBJECTE", "ESTATUS", "BELLESA", "JOVENTUT", "PERTINENÇA", "ÈXIT"] },
  /* 35 */ { type: "bin", labels: ["ENCARA FUNCIONA", "PAPERERA", "VIDA ÚTIL"] },
  /* 36 */ { type: "clock", labels: ["24 HORES", "TEMPS CAPTURAT, FINS I TOT LA NIT"] },
  /* 37 */ { type: "tree", labels: ["TRONC COMÚ", "BRANQUES DIFERENTS"] },
  /* 38 */ { type: "rounds", mode: "filter", labels: ["PRESSIÓ", "RESISTENTS"] },
  /* 39 */ { type: "rounds", mode: "generations", labels: ["GENERACIONS", "BARRERA"] },
  /* 40 */ { type: "camouflage", labels: ["AMENAÇA", "NORMALITAT"] },
  /* 41 */ { type: "ground", mode: "seeds", labels: ["APARENT VICTÒRIA", "LLAVORS LATENTS"] },
  /* 42 */ { type: "network", mode: "defector", labels: ["ESPAI OCUPAT", "EXPANSIÓ"] },
  /* 43 */ { type: "radial", mode: "branches", labels: ["ESPAI SATURAT", "ZONES NOVES"] },
  /* 44 */ { type: "radial", mode: "compartments", labels: ["PAÏSOS · CLASSES · CULTURES · LLENGÜES", "LA FLETXA TRAVESSA TOTES LES PARETS"] },
  /* 45 */ { type: "parcels", labels: ["VIDA QUOTIDIANA", "PARCEL·LES AMB PREU"] },
  /* 46 */ { type: "converge", labels: ["TERRITORI OCUPAT", "CENTRE EXTERIOR"], fromRing: true, n: 7 },
  /* 47 */ { type: "twin", labels: ["SENSE DECISIÓ", "AMB BANDERA I EXÈRCIT"] },
  /* 48 */ { type: "eat", labels: ["EL C", "LA BASE QUE EL SOSTÉ"] },
  /* 49 */ { type: "outflow", back: true, labels: ["PLANETA TANCAT", "EL RESIDU TORNA AL COS"] },
  /* 50 */ { type: "curves", kind: "hidden", labels: ["LÍMIT OCULT", "CRISI"] },
  /* 51 */ { type: "curves", kind: "crossing", labels: ["BENEFICI LOCAL", "CONDICIONS GLOBALS"] },
  /* 52 */ { type: "network", mode: "compare", labels: ["XARXA DIVERSA", "XARXA UNIFORME"] },
  /* 53 */ { type: "sequence", rows: [["PRODUCTE", "EXPOSICIÓ", "DANY", "TUMOR", "SÍMPTOMA"]], marker: 0 },
  /* 54 */ { type: "tap", labels: ["FONT INTACTA", "EL DANY CONTINUA"] },
  /* 55 */ { type: "pattern", labels: ["SENYALS DISPERSOS", "UN MATEIX PATRÓ"] },
  /* 56 */ { type: "orbit", mode: "bignumber", labels: ["+ PIB", "SALUT", "DISTRIBUCIÓ", "TEMPS", "NATURA"] },
  /* 57 */ { type: "orbit", mode: "dashboard", labels: ["SALUT DEL SISTEMA", "SALUT", "TEMPS", "DISTRIBUCIÓ", "EMISSIONS", "VINCLES", "VOLUM"] },
  /* 58 */ { type: "excise", labels: ["MARGE", "JA ERA FORA"] },
  /* 59 */ { type: "ground", mode: "roots", labels: ["LA MASSA REDUÏDA", "LES ARRELS INTACTES"] },
  /* 60 */ { type: "network", mode: "rewire", labels: ["TREURE EL CENTRE", "REDISSENYAR ELS FLUXOS"] },
  /* 61 */ { type: "shield", mode: "protect", labels: ["INTERVENCIÓ", "ZONES VULNERABLES PROTEGIDES"] },
  /* 62 */ { type: "balance", labels: ["COSTOS DE LA TRANSICIÓ", "REPARTITS, NO CONCENTRATS"] },
  /* 63 */ { type: "orbit", mode: "encircle", labels: ["EXPANSIÓ NOCIVA", "CIÈNCIA", "SINDICATS", "PREMSA", "SERVEIS PÚBLICS", "COMUNITATS"] },
  /* 64 */ { type: "shield", mode: "brake", labels: ["DEFENSA", "AMB FRE SOBRE SI MATEIXA"] },
  /* 65 */ { type: "ground", mode: "pipes", labels: ["CANVIEN ELS GESTORS", "LES CANONADES NO"] },
  /* 66 */ { type: "curves", kind: "threshold", labels: ["LLINDAR DE DETECCIÓ", "ENCARA ACTIU"] },
  /* 67 */ { type: "curves", kind: "stops", labels: ["CRÉIXER FINS ON CAL, I ATURAR-SE"] },
  /* 68 */ { type: "curves", kind: "sufficiency", labels: ["PROU PER A TOTHOM"] },
  /* 69 */ { type: "network", mode: "sectors", labels: ["VIDA", "SALUT", "EDUCACIÓ", "CURES", "CIÈNCIA", "HABITATGE"] },
  /* 70 */ { type: "curves", kind: "twolines", labels: ["REGENERATIU", "DESTRUCTIU", "RECONVERSIÓ"] },
  /* 71 */ { type: "orbit", mode: "protected", labels: ["FORA DEL PREU", "SALUT", "AIGUA", "HABITATGE", "EDUCACIÓ", "ENERGIA"] },
  /* 72 */ { type: "network", mode: "decentralize", labels: ["UN CENTRE", "MOLTS CENTRES"] },
  /* 73 */ { type: "three", labels: ["COMUNS", "COOPERATIVES", "SERVEIS PÚBLICS"] },
  /* 74 */ { type: "network", mode: "nocenter", labels: ["DIFERÈNCIES CONNECTADES", "CAP PART NO OCUPA EL CENTRE"] },
  /* 75 */ { type: "sequence", rows: [["OBSERVAR", "ACTUAR", "AVALUAR", "CORREGIR"]], loop: true },
  /* 76 */ { type: "network", mode: "regulated", labels: ["EL COS COMÚ DECIDEIX", "ENTRADES · SORTIDES · LÍMITS"] }
];

export const DIAGRAM_SPECS = specs.map((spec, index) => ({ node: index + 1, ...spec }));

if (DIAGRAM_SPECS.length !== 76) throw new Error(`Catàleg visual incomplet: ${DIAGRAM_SPECS.length}/76`);
